name: 'Build Release'

on:
  push:
    branches: ["Release"]

jobs:
  Building:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Setup .NET
        uses: actions/setup-dotnet@v6
        with:
          dotnet-version: 10.x
      - name: Fill current commit hash in for program
        run: sed -i "s|Not a release commit|$(git rev-parse HEAD)|" NTH/PipelineGitCommit.cs
      - name: Test Release
        run: dotnet test --solution NTH.slnx -c Release --progress true --settings .runsettings --coverage
      - name: Publish Release
        run: dotnet publish -p:PublishProfile=NTH/Properties/PublishProfiles/LinuxReleaseProfile.pubxml NTH/NTH.csproj
      - name: list files
        run: ls -alF
      - name: list NTH files
        run: ls -alF NTH/
      - name: list output folder
        run: ls -alF /home/runner/work/NoTransactionHelps/NoTransactionHelps/NTH/bin/Release/net10.0/linux-x64/publish/
